application: sudoku-insight
version: 1-dev
runtime: java
threadsafe: true

handlers:

- url: /rpc
  secure: always
  servlet: us.blanshard.sudoku.appengine.RpcServlet

- url: /
  secure: optional
  servlet: us.blanshard.sudoku.appengine.TopServlet


system_properties:
  java.util.logging.config.file: WEB-INF/logging.properties

