application: sudoku-insight
version: 1-dev
runtime: java
threadsafe: true

handlers:

- url: /rpc
  secure: always
  servlet: us.blanshard.sudoku.appengine.RpcServlet

- url: /profile
  secure: always
  servlet: us.blanshard.sudoku.appengine.ProfileServlet
  login: required

- url: /installation
  secure: always
  servlet: us.blanshard.sudoku.appengine.InstallationServlet

- url: /attempt
  secure: always
  servlet: us.blanshard.sudoku.appengine.AttemptServlet

- url: /vote
  secure: always
  servlet: us.blanshard.sudoku.appengine.VoteServlet

- url: /
  secure: optional
  servlet: us.blanshard.sudoku.appengine.TopServlet


system_properties:
  java.util.logging.config.file: WEB-INF/logging.properties

